package edu.umich.lib.dor.replicaexperiment.exception;

public class ChecksumCalculationException extends RuntimeException {
    public ChecksumCalculationException(String message, Throwable cause) {
        super(message, cause);
    }
}
